### PR TITLE
Hotfix python3 support

### PR DESCRIPTION
**Pull request by mihaha**
Python3 support got broken after PR https://github.com/lukalabs/cakechat/pull/25/files
I fixed it

### CODE REVIEW

**Comment by mihaha** [comment]
`np.load('non_existent_dir/tmp.txt')` perfectly raises

IOError: [Errno 2] No such file or directory: 'non_existent_dir/tmp.txt'

which is exactly what we need in when we don't have the model available. I would leave it like that: without ensure_dir

**Comment by nicolas-ivanov** [comment]
Previously 'ensure_dir' was in 'save_model' function, not in 'load_weights':
https://github.com/lukalabs/cakechat/pull/25/files#diff-7ce0c0a0b1ecbed6c0c110231e403466L632

And in case there is no specified directory to save your model to, 'ensure_dir' will create it for you, which might save you from rerunning your experiment. 

I still suggest to bring this function call back.

**Comment by mihaha** [comment]
@nicolas-ivanov done

**Comment by nicolas-ivanov** [comment]
Awesome!

**Pull request merged**
